/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ClienteServidor
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class grafo : TBase
  {
    private List<vertice> _ListaVertices;
    private List<aresta> _ListaAresta;

    public List<vertice> ListaVertices
    {
      get
      {
        return _ListaVertices;
      }
      set
      {
        __isset.ListaVertices = true;
        this._ListaVertices = value;
      }
    }

    public List<aresta> ListaAresta
    {
      get
      {
        return _ListaAresta;
      }
      set
      {
        __isset.ListaAresta = true;
        this._ListaAresta = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ListaVertices;
      public bool ListaAresta;
    }

    public grafo() {
            this.ListaVertices = new List<vertice>();
            this.ListaAresta = new List<aresta>();
        }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  ListaVertices = new List<vertice>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    vertice _elem2;
                    _elem2 = new vertice();
                    _elem2.Read(iprot);
                    ListaVertices.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  ListaAresta = new List<aresta>();
                  TList _list3 = iprot.ReadListBegin();
                  for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                  {
                    aresta _elem5;
                    _elem5 = new aresta();
                    _elem5.Read(iprot);
                    ListaAresta.Add(_elem5);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("grafo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ListaVertices != null && __isset.ListaVertices) {
          field.Name = "ListaVertices";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, ListaVertices.Count));
            foreach (vertice _iter6 in ListaVertices)
            {
              _iter6.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (ListaAresta != null && __isset.ListaAresta) {
          field.Name = "ListaAresta";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, ListaAresta.Count));
            foreach (aresta _iter7 in ListaAresta)
            {
              _iter7.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("grafo(");
      bool __first = true;
      if (ListaVertices != null && __isset.ListaVertices) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ListaVertices: ");
        __sb.Append(ListaVertices);
      }
      if (ListaAresta != null && __isset.ListaAresta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ListaAresta: ");
        __sb.Append(ListaAresta);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
